# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Samuele Padula
title: Happy Hacking!
email: job@samuelepadula.it
website: https://samuelepadula.it

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username: padowla
# stackoverflow_username: "00000001"
# flickr_username: jekyll
# instagram_username: jameswgrant
linkedin_username: ilucano

# Additional icon links
additional_links:
  - title: HackTheBox
    icon: fas fa-cube
    url: https://app.hackthebox.com/profile/107027

# About Section
about:
  title: Hello World!
  profile_image: images/profile.jpg
  content: |
    <p style='text-align:center;'>As you can see my site reflects my IT nature, <b>"backendist"</b> & <b>minimalist</b>. I love security, networking, and everything the end user does not see. But I find very boring to try to describe myself with an 'About me'.<br>Write me and let's talk.<br>Maybe with a :beer:</p>
    <p style='text-align:center;'><a href="Samuele_Padula_CV.pdf">Enjoy my CV!</a></p>
    <p style='text-align:center;'><a href="https://learn.samuelepadula.it">Hack with me</a></p>

# Experience Section
experience:
  title: Experience
  layout: list
  content:
    - layout: left
      title: Deloitte NextHub S.r.l
      link: https://www.deloitte.com
      link_text: Deloitte
      sub_title: CyberSecurity Consultant - Red Team Operator
      caption: April 2024 - Current
      description: |
        - Vulnerability Assessment
        - Perform Web Application and Infrastructure Penetration Tests in a black/gray-box approach
        - Golden Image Security Assessment
        - Active Directory security posture testing
        - Contribution to the development and improvement of security testing methodologies, tools and processes in client’s companies.
    - layout: left
      title: Innovery s.p.a
      link: https://www.innovery.net
      link_text: Innovery
      sub_title: Security Operation Center Analyst - Managed Detection and Response
      caption: September 2023 - January 2024
      description: |
        - Incident analysis using SIEMs such as IBM QRadar, Azure Sentinel, Crowdstrike and Splunk.
        - Analysis of phishing attacks via the Email protection solution of Proofpoint Email.

# Education Section
education:
  title: Education
  layout: list
  content:
    - layout: top-middle
      title: Innovery Academy Basilicata
      caption: May 2023 - September 2023
      sub_title: https://www.innovery.net/academy-innovery-basilicata/
      description: |
        <a href="Course_Program_Innovery_Academy.pdf">Read the course program here!</a>
    - layout: top-middle
      title: Università di Pisa
      caption: February 2023 - February 2024
      sub_title: First-level Master in Cybersecurity
      description: |
        CFU: 60
        Modules details:
          - Python Course
          - Data mining
          - Networking
          - Web technology
          - Applied cryptography
          - Network Security and Ethical hacking
          - Operating Systems Security
          - Digital Forensics
          - Cyber Intelligence
          - Complex network analysis
          - Regulations on general data protection, GDPR and cybersecurity
          - Java Fundamentals Course
          - LAB Secure System Configuration
          - LAB on DNS, DNSSEC
          - LAB on Secure Tool
          - Mobile and cloud security
        Thesis: DEMIoT, a secure microservices IoT environment <a href="Thesis_First_Level_Master_Cybersec_Unipisa.pdf">(View the thesis work)</a>

# A Little More About Me
more_about_me:
  title: A Little More About Me
  layout: text
  content: |
    Alongside my interests in networks, security and computer engineering, some of my other interests and hobbies are:
    - Bouldering, Trekking and bushcraft
    - <a href="https://www.magazzinisociali.com">Volunteering</a>
    - DIY and handmade

# Footer
#footer_show_references: true
#quote: >

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
  - jemoji
  - jekyll-redirect-from

theme: jekyll-theme-hacker
