# Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Samuele Padula
title: ICT Cloud Consultant
email: samuelepadula@gmail.com
website: https://padowla.github.io/

# Dark Mode (true/false/never)
darkmode: true

# Social links
#twitter_username: facespics
github_username:  padowla
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: ilucano
# xing_username: jekyll
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: itsgoingto.be
#  icon: fas fa-globe
#  url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
#about_content: | # this will include new lines to allow paragraphs
about_content: <p style="text-align:center;">I find it very reductive and boring to try to describe myself with an "About me".<br>Write me and let's talk.<br>Maybe with a :beer:</p>
content:
  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Super awesome project
        link: github.com/sproogen
        # link_text: Project Website
        additional_links:
          - title:  sproogen/modern-resume-theme
            icon: fab fa-github
            url: github.com/sproogen/modern-resume-theme
          # - title:  Github page for project (eg. sproogen/modern-resume-theme)
          #   icon: fab fa-github
          #   url: Link to project (eg. sproogen.github.io/modern-resume-theme)
        quote: >
          This is probably one of the greatest apps ever created, if you don't agree you're probably wrong.
        description: | # this will include new lines to allow paragraphs
          I started this project as a way if learning <mark>React</mark> and it has since grown into a fully fledged app. I have learned many skills through this and been I'm very proud of having this in my portfolio. If you don't have a project as awesome as this I would advise you make one.

  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: iCubed s.r.l
        link: icubed.it
        link_text: icubed.it
        sub_title: ICT Consultant - Cloud
        caption: May 2021 - Present
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Design, management and maintenance of cloud and on-premises infrastructure for a leading European energy company. Azure IaaS deployment, Azure IoT, management and deployment with ARM templates, Powershell, MSSQL Server, cost and resource management, Azure Kubernetes Service and migration from RedHat OpenShif (AKS over HCI), Azure Container Registry, RabbitMQ

      - layout: left
        title: LantechLongwave s.p.a
        link: https://www.lantechlongwave.it/
        link_text: www.lantechlongwave.it
        sub_title: Junior Network Engineer
        caption: Jan 2021 - May 2021
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            Operator of a Network Operation Center to support public and private companies. Maintenance and management of routers, switches, access points (Cisco, Aruba, HP, PaloAlto, Fortinet). Network analysis and backup, Documentation and reporting, Configuration and maintenance of Icinga, Neteye and NeDi monitoring tools for the new NOC Platform. Data integration and analysis via InfluxDB and Grafana, Unix/Linux Systems (CentOS, RedHat Enterprise)
 
      - layout: left
        title: Servizidoc s.r.l.s
        link: https://www.servizidoc.com/
        link_text: www.servizidoc.com
        sub_title: Junior Network Engineer
        caption: Jan 2016 - Jan 2018
        #quote: >
        #  Solving 21st century problems by diging holes and making game changing products like the *not a flamethrower*
        description: | # this will include new lines to allow paragraphs
            IT operations and support. Network mainteinance and Hardware and software support
            
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Università di Pisa
        caption: Nov 2021 - Sep 2021
        sub_title: Master ’s Degree in Computer Security LM-66
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Exams obtained: 3/12 [Data and system security,Language-based technology for security,Systems and Languages for Informatics] <br> CFU achieved: 30/120

      - layout: left
        title: eForhum Milano
        caption: Oct 2020 - Nov 2020
        sub_title: Cisco Networking Academy - CCNAv7
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          CCNA 200- 301 Talent con percorso di certificazione offerto da Lantech Longwave 
 
      - layout: left
        title: Università degli studi di Ferrara
        caption: Sep 2017 - Sep 2020
        sub_title: Bachelor’s Degree in Computer and Electronic Engineering L-8 (Web systems)
        #quote: >
        #  Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        description: | # this will include new lines to allow paragraphs
          Evaluation: 110/110 <br> Thesis: Monitoring of an IT infrastructure by means of Open Source technologies: study and simulation


  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks, security and computer engineering some of my other interests and hobbies are:
      - Trekking and bushcraft
      - Volunteering at magazzinisociali.com
      - DIY and handmade


# Footer
footer_show_references: true
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
 - jemoji
